[theme]
base="light"
primaryColor="#0369a1"
backgroundColor="#F5F3EE"
secondaryBackgroundColor="#e2e8f0"
textColor="#0f172a"

[server]
port = 8080
address = "0.0.0.0"
headless = true

[browser]
gatherUsageStats = false